### ISSUE TITLE
info

### ISSUE THREAD

**Issue by ciaoamigoschat** [0-u-0/dugon-media-server#1]
Hi can I know the purpose of the project? I'm looking at a simple to use media server.

**Comment by craterone** [comment]
Hi, sorry for the reply.
I want to make a project for the guys who even don't know WebRTC can use it to build a real-time software easily.
The  architecture  of this project:

![architecture](https://user-images.githubusercontent.com/47512039/81493162-1d93b780-92d9-11ea-9ebd-fc91fd8ef21b.png)

I hope it's helpful, :) .
